### ISSUE TITLE
HtmlInputWithoutRequirementOfEncodingBeforeOutput doesn't work as expected

### ISSUE THREAD

**Issue by gswartz777** [CompuMasterGmbH/CompuMaster.Text.Diff#1]
From the read me file I'm expecting that by using HtmlInputWithoutRequirementOfEncodingBeforeOutput, the diff is expecting to receive html and won't do any encoding of it.  I'm passing in two html strings for comparison and all of the html is being encoded in the result.  How can I prevent this?  Thanks.

`model.Differences = Diffs.DumpDiffAsHtml(model.OriginalLanguage.Introduction, model.NewLanguage.Introduction,
                Diffs.EncodingRequirement.HtmlInputWithoutRequirementOfEncodingBeforeOutput, true);`

**Comment by jochenwezel** [comment]
Have you got some test data for reproduction purposes?
1. Input data
2. Current output
3. Expected output

**Comment by jochenwezel** [comment]
Closed due to inactivity; if there is any test case, please just re-open with some test data, current result and expected result
